### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by mimikatzz** [Zyllow1/Skating#1]
Hi, when I want to start using the skateboard item I can't do it. Do you know how to do it ?

**Comment by Zyllow1** [comment]
Check that you have followed the following tutorial:

# Dependencies:

- [Ox_inventory](https://github.com/overextended/ox_inventory/releases/tag/v2.35.1)
- **Framework :** `ESX or QBCore`

# Installation : 

- **Step 1 :** Add the following line in `ox_inventory/data/items.lua`

```
  ["skateboard"] = {
		label = "skateboard", 
		weight = 1,
		stack = true,
		close = true,
	},
```

- **Step 2:** Then add the image to the `assets/inventory_images` folder : `ox_inventory/web/images`


# ENJOY ! 🫡

**Comment by mimikatzz** [comment]
ok

**Comment by mimikatzz** [comment]
I haven't seen the guide...
